-- Traffic Dashboard — Schema inicial
-- Tabelas: clients, client_accounts, account_balance, meta_ads_raw_data

-- ============================================================
-- Tabelas
-- ============================================================

create table if not exists meta_ads_raw_data (
  id                       bigint generated by default as identity primary key,
  data                     date not null,
  cliente_id               text not null,
  ad_id                    text not null,
  campanha                 text,
  anuncio                  text,
  alcance                  integer default 0,
  impressoes               integer default 0,
  cliques                  integer default 0,
  resultados               integer default 0,
  mensagens_iniciadas      integer default 0,
  comentarios              integer default 0,
  salvos                   integer default 0,
  cpc                      numeric default 0,
  cpm                      numeric default 0,
  ctr                      numeric default 0,
  custo_por_lead           numeric default 0,
  custo_por_mensagem       numeric default 0,
  custo_total              numeric default 0,
  thumbnail_url            text,
  link_anuncio             text,
  created_at               timestamptz default now(),
  account_name             text,
  instagram_profile_visits integer default 0,
  leads                    integer default 0,
  add_to_cart              integer default 0,
  purchases                integer default 0,
  initiate_checkout        integer default 0,
  purchase_value           numeric default 0,
  compartilhamentos        integer default 0,
  data_inicio              date,
  data_fim                 date,
  custo_por_resultado      numeric,
  thumbnail_storage_url    text,
  image_url                text,
  creative_id              text,
  unique (ad_id, data)
);

create index if not exists meta_ads_raw_data_cliente_data_idx on meta_ads_raw_data (cliente_id, data desc);
create index if not exists meta_ads_raw_data_ad_id_idx        on meta_ads_raw_data (ad_id, data desc);

create table if not exists clients (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  logo_url text,
  status text default 'active', -- active | paused | alert
  notes text,
  created_at timestamptz default now()
);

create table if not exists client_accounts (
  id uuid primary key default gen_random_uuid(),
  client_id uuid references clients(id) on delete cascade,
  platform text not null, -- 'meta' | 'google'
  account_id text not null unique,
  account_name text,
  alert_threshold numeric default 200,
  created_at timestamptz default now()
);

create table if not exists account_balance (
  id uuid primary key default gen_random_uuid(),
  account_id uuid references client_accounts(id) on delete cascade unique,
  balance numeric default 0,
  currency text default 'BRL',
  updated_at timestamptz default now(),
  alert_sent_at timestamptz
);

-- ============================================================
-- RLS — leitura para usuários autenticados; escrita via service role
-- ============================================================

alter table clients enable row level security;
alter table client_accounts enable row level security;
alter table account_balance enable row level security;
alter table meta_ads_raw_data enable row level security;

create policy "authenticated read clients"
  on clients for select to authenticated using (true);

create policy "authenticated update clients"
  on clients for update to authenticated using (true) with check (true);

create policy "authenticated read client_accounts"
  on client_accounts for select to authenticated using (true);

create policy "authenticated update client_accounts"
  on client_accounts for update to authenticated using (true) with check (true);

create policy "authenticated read account_balance"
  on account_balance for select to authenticated using (true);

create policy "authenticated read meta_ads_raw_data"
  on meta_ads_raw_data for select to authenticated using (true);

-- O workflow n8n usa a anon key para fazer upsert de métricas
create policy "anon upsert meta_ads_raw_data"
  on meta_ads_raw_data for all to anon using (true) with check (true);
